---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: guide-helper
spec:
  encryptedData:
    JWT_SECRET: AgCFhC58sf30N6HluuZ5MurskpAuytAl8K/vCOG0ka8Q80O+DTwCHlNtiyfqoMtS5p/ntAePL0FvQMGLrLud6yFfVpzmgd76fhLRIZah92AmhEHxk1RZjpZl5Eq8i5i+yJQJQCIJvC6lJW4LiWGDXNXn8qs8o3de4Uuf3KPJcvob80bCFqZu+aMTPhnbjLEyC3F1qhbptVrpWjezy2n8PR9K9IgKeyzTFl3v1ykFqWstP36qC13l3u7mJD6Z0iZYRCs5FQ4BCaVD7d3t+Z/4XyjKBke55f0CplIhU7fLeNdgC55aOMm+PzX/xMOlYW0tG5SCxjpXe2V2OUm5MWaZ/icKK/9LNpmQIJBddlW1psL9Kx3kZdKRxs8JUYSfCkBKaCA+/FTmwwQJeskrvx2aEZLmjfEzDZcFtAYUlKk2Vn97xwqJ4gy6lar41eQqvLWLimGQApwZDvI8rnuCjiZMDd4dz+y77bwXgI5Xx42eXPRgBe9tlixZ4d2i/pZf5dDvT+J6nL0qQzgLmw3O2yO4bF/V5T5oDlGZg3TXd7S0ihPO+ANXu2lgQ944GvbxMNr6f60adA6evu3O1Wv5wTi6XdffWQZ6zZDCSiHqB7k6ScxAbeJ14bCeIU3r96mgywqr4o/YZdIwnfTfOh8zI9eajcxTO5ZO6ECdCdEoUQE5xbFfGDQhEmNtUD3JRwQyztcsyOACHfyOCyqzkCtT8Tvrd9IYkcLmRB9EDTOJBbKRRGuc1X0v2t8=
  template:
    metadata:
      name: auth-secret
      namespace: guide-helper
    type: Opaque
