---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: guide-helper
spec:
  encryptedData:
    .dockerconfigjson: AgAnB+Kz10D1wdyu0JE4iBGYNOKC9C5hbY31ly6JgSM8CkL0FTCSQvaZvwnBYlcGmRPoeayTE7PmoJHuew3oD4n587CfPWsXWZhbmAoPG6zDrnx5c4VVd/5iYytGFrP7IUYCHlvLCxkJsUfIhds1YZZrWB6Apd1G+4QPrzFaILMRggnQktTDP4PXuyMtSeWhw6YdEFxQ16Mh//eyaINpk7e8WAQhqHg67rTK+ZN/S3LtrUWWnAnsKwJm1tTgJqVgCLHOMkPXCeHQaagBlmmJOzTEZl60TKUiAyoVsTSL5Z4/dpY6FT7Mm/olWSDJzd4XaZxsubn2dwu8HKrUGlJVHG80QY1102HojkutyNRumWVjBTvHlonMRfvrzWOeobiNk6J2gooUhSmhZGZxCcI7mH9FSg0C3ssypMlsTo0tN+ZN7Zi6ggh/K2jNz86kIQPPpMHbuAJAKIqVxlGTKxqaxnaKwpADq3fp7fyP2jQnGKkWZYJThy7bFQdYZeNRjXu5TUffsRHJat29f7HnsKuZmcOglFXF58Hk7WPXbLRWDyiqDoxzrWBkqT16Luul5M/GmENyyQ/0nTpEu+EWzrDzy8PmbmJeKGus2EtZjE/pO5K8jbSd51f4HmeoEj7wlR/NR1RR4ACybidutUnRcgoWtM84FbrIgkWxqEk+VcNf6RL9K3mN8Fs/abtx+WvRkZvm78YfAive0Cpk2xMsWgl8Fp+bYMr7VsV1paEJSNGIicI3DR9paAuG6TJMdSkrJXTqT71XEpXKI44WQWtsn6vAX8p6j5ORy5cMHY9aI1m2gfJdgB4VoDkdbbxql4Sa5+El9fC4gauJRNQt5/mfsyEvJNm4dAVn42pAlYi8CXKIUO4Qm0nMRdjIADbDx20ya6JwffQzxQMQHSQ3Fa5sZLITZHf5p6elHihVKGoNs/H4hZq1w7EAELvf2A041k2Jou5EzKs/URrfPdZRjoduQ1jFrdxDgSyUVH69ON4=
  template:
    metadata:
      name: ghcr-secret
      namespace: guide-helper
    type: kubernetes.io/dockerconfigjson
