apiVersion: v1
kind: ConfigMap
metadata:
  name: tiles-config
data:
  HTTP_SERVER_PORT: "8080"
  LOGGER_LEVEL: "info"
  TELEMETRY_ENABLED: "true"
  TELEMETRY_SERVICE_NAME: "guide-helper-tiles"
  TELEMETRY_SERVICE_VERSION: "1.0.0"
  TELEMETRY_ENVIRONMENT: "production"
  TELEMETRY_OTLP_ENDPOINT: "otel-collector.observability.svc.cluster.local:4317"
  CACHE_BASE_URL: "http://cache:8080"
  UPSTREAM_TILE_SERVER_URL: "https://tile.openstreetmap.org"
