apiVersion: v1
kind: ConfigMap
metadata:
  name: tiles-config
data:
  HTTP_SERVER_PORT: "8080"
  LOGGER_LEVEL: "info"
  CACHE_BASE_URL: "http://cache:8080"
  UPSTREAM_TILE_SERVER_URL: "https://tile.openstreetmap.org"
