apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guide-helper

resources:
  - namespace.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - auth/configmap.yaml
  - auth/deployment.yaml
  - auth/service.yaml
  - cache/configmap.yaml
  - cache/deployment.yaml
  - cache/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml

images:
  - name: cache
    newName: ghcr.io/jaennil/guide-helper-cache
    newTag: latest
  - name: auth
    newName: ghcr.io/jaennil/guide-helper-auth
    newTag: latest
  - name: frontend
    newName: ghcr.io/jaennil/guide-helper-frontend
    newTag: latest
