apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guide-helper

resources:
  - namespace.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - auth/configmap.yaml
  - auth/deployment.yaml
  - auth/service.yaml
  - cache/configmap.yaml
  - cache/deployment.yaml
  - cache/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - tuna/deployment.yaml
