apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guide-helper

resources:
  - namespace.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - redis/pvc.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - auth/configmap.yaml
  - auth/deployment.yaml
  - auth/service.yaml
  - auth/servicemonitor.yaml
  - routes/configmap.yaml
  - routes/deployment.yaml
  - routes/service.yaml
  - cache/configmap.yaml
  - cache/deployment.yaml
  - cache/service.yaml
  - cache/servicemonitor.yaml
  - tiles/configmap.yaml
  - tiles/deployment.yaml
  - tiles/service.yaml
  - tiles/servicemonitor.yaml
  - dashboard.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
